# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\TCMC\W\UI\para.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(691, 570)
        self.baseSizeGroupBox = QtWidgets.QGroupBox(Form)
        self.baseSizeGroupBox.setGeometry(QtCore.QRect(50, 70, 171, 161))
        self.baseSizeGroupBox.setObjectName("baseSizeGroupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.baseSizeGroupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 131, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.baseSizeVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.baseSizeVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.baseSizeVerticalLayout.setObjectName("baseSizeVerticalLayout")
        self.baseLengthLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.baseLengthLabel.setObjectName("baseLengthLabel")
        self.baseSizeVerticalLayout.addWidget(self.baseLengthLabel)
        self.baseLengthLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.baseLengthLineEdit.setObjectName("baseLengthLineEdit")
        self.baseSizeVerticalLayout.addWidget(self.baseLengthLineEdit)
        self.baseWidthLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.baseWidthLabel.setObjectName("baseWidthLabel")
        self.baseSizeVerticalLayout.addWidget(self.baseWidthLabel)
        self.baseWidthLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.baseWidthLineEdit.setObjectName("baseWidthLineEdit")
        self.baseSizeVerticalLayout.addWidget(self.baseWidthLineEdit)
        self.baseThickLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.baseThickLabel.setObjectName("baseThickLabel")
        self.baseSizeVerticalLayout.addWidget(self.baseThickLabel)
        self.baseThickLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.baseThickLineEdit.setObjectName("baseThickLineEdit")
        self.baseSizeVerticalLayout.addWidget(self.baseThickLineEdit)
        self.materialGroupBox = QtWidgets.QGroupBox(Form)
        self.materialGroupBox.setGeometry(QtCore.QRect(230, 70, 211, 161))
        self.materialGroupBox.setObjectName("materialGroupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.materialGroupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 131, 128))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.materialVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.materialVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.materialVerticalLayout.setObjectName("materialVerticalLayout")
        self.cementLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.cementLabel.setObjectName("cementLabel")
        self.materialVerticalLayout.addWidget(self.cementLabel)
        self.cementLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.cementLineEdit.setObjectName("cementLineEdit")
        self.materialVerticalLayout.addWidget(self.cementLineEdit)
        self.ashLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.ashLabel.setObjectName("ashLabel")
        self.materialVerticalLayout.addWidget(self.ashLabel)
        self.ashLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.ashLineEdit.setObjectName("ashLineEdit")
        self.materialVerticalLayout.addWidget(self.ashLineEdit)
        self.slagLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.slagLabel.setObjectName("slagLabel")
        self.materialVerticalLayout.addWidget(self.slagLabel)
        self.slagLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.slagLineEdit.setObjectName("slagLineEdit")
        self.materialVerticalLayout.addWidget(self.slagLineEdit)
        self.maintainGroupBox = QtWidgets.QGroupBox(Form)
        self.maintainGroupBox.setGeometry(QtCore.QRect(460, 70, 181, 161))
        self.maintainGroupBox.setObjectName("maintainGroupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.maintainGroupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 141, 131))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.maintainVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.maintainVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.maintainVerticalLayout.setObjectName("maintainVerticalLayout")
        self.concreteTempLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.concreteTempLabel.setObjectName("concreteTempLabel")
        self.maintainVerticalLayout.addWidget(self.concreteTempLabel)
        self.concreteTempLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.concreteTempLineEdit.setObjectName("concreteTempLineEdit")
        self.maintainVerticalLayout.addWidget(self.concreteTempLineEdit)
        self.coverLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.coverLabel.setObjectName("coverLabel")
        self.maintainVerticalLayout.addWidget(self.coverLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.converYesCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.converYesCheckBox.setObjectName("converYesCheckBox")
        self.horizontalLayout.addWidget(self.converYesCheckBox)
        self.coverNoCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.coverNoCheckBox.setObjectName("coverNoCheckBox")
        self.horizontalLayout.addWidget(self.coverNoCheckBox)
        self.maintainVerticalLayout.addLayout(self.horizontalLayout)
        
        self.WaterGroupBox = QtWidgets.QGroupBox(Form)
        self.WaterGroupBox.setGeometry(QtCore.QRect(60, 250, 381, 121))
        self.WaterGroupBox.setObjectName("WaterGroupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.WaterGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.waterFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.waterFormLayout.setContentsMargins(0, 0, 0, 0)
        self.waterFormLayout.setObjectName("waterFormLayout")
        
        self.waterSpeedLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.waterSpeedLabel.setObjectName("waterSpeedLabel")
        self.waterFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.waterSpeedLabel)
        self.waterSpeedLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waterSpeedLineEdit.setObjectName("waterSpeedLineEdit")
        self.waterFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.waterSpeedLineEdit)
        self.deltaTempLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.deltaTempLabel.setObjectName("deltaTempLabel")
        self.waterFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.deltaTempLabel)
        self.deltaTempLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.deltaTempLineEdit.setObjectName("deltaTempLineEdit")
        self.waterFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deltaTempLineEdit)
        self.maxPipeLengthLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.maxPipeLengthLabel.setObjectName("maxPipeLengthLabel")
        self.waterFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.maxPipeLengthLabel)
        self.maxPipeLengthLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.maxPipeLengthLineEdit.setObjectName("maxPipeLengthLineEdit")
        self.waterFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxPipeLengthLineEdit)
        
        
        self.PipeArrangeGroupBox = QtWidgets.QGroupBox(Form)
        self.PipeArrangeGroupBox.setGeometry(QtCore.QRect(60, 380, 361, 61))
        self.PipeArrangeGroupBox.setObjectName("PipeArrangeGroupBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.PipeArrangeGroupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.PipeArrangeHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.PipeArrangeHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.PipeArrangeHorizontalLayout.setObjectName("PipeArrangeHorizontalLayout")
        self.PipeArrangeYesCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.PipeArrangeYesCheckBox.setObjectName("PipeArrangeYesCheckBox")
        self.PipeArrangeHorizontalLayout.addWidget(self.PipeArrangeYesCheckBox)
        self.PipeArrangeNoCheckBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.PipeArrangeNoCheckBox.setObjectName("PipeArrangeNoCheckBox")
        self.PipeArrangeHorizontalLayout.addWidget(self.PipeArrangeNoCheckBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(470, 310, 166, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        
        self.YesNohorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.YesNohorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.YesNohorizontalLayout.setObjectName("YesNohorizontalLayout")
        self.YesPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.YesPushButton.setObjectName("YesPushButton")
        self.YesNohorizontalLayout.addWidget(self.YesPushButton)
        self.NoPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.NoPushButton.setObjectName("NoPushButton")
        self.YesNohorizontalLayout.addWidget(self.NoPushButton)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 460, 601, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.baseSizeGroupBox.setTitle(_translate("Form", "基础尺寸"))
        self.baseLengthLabel.setText(_translate("Form", "基础长度(m)"))
        self.baseWidthLabel.setText(_translate("Form", "基础宽度(m)"))
        self.baseThickLabel.setText(_translate("Form", "基础厚度(m)"))
        self.materialGroupBox.setTitle(_translate("Form", "单位体积混凝土中的材料用量(kg/m3)"))
        self.cementLabel.setText(_translate("Form", "水泥"))
        self.ashLabel.setText(_translate("Form", "粉煤灰"))
        self.slagLabel.setText(_translate("Form", "矿渣"))
        self.maintainGroupBox.setTitle(_translate("Form", "浇筑养护条件"))
        self.concreteTempLabel.setText(_translate("Form", "混凝土入模温度"))
        self.coverLabel.setText(_translate("Form", "基础表面是否覆盖保温层"))
        self.converYesCheckBox.setText(_translate("Form", "是"))
        self.coverNoCheckBox.setText(_translate("Form", "否"))
        self.WaterGroupBox.setTitle(_translate("Form", "冷水水参数"))
        self.waterSpeedLabel.setText(_translate("Form", "冷却水流量（0.8～3.2m3/h)"))
        self.deltaTempLabel.setText(_translate("Form", "冷却水入管温度与混凝土入模温度之差（0～20℃)"))
        self.maxPipeLengthLabel.setText(_translate("Form", "冷却水管最长单圈长度(0～200m)"))
        self.PipeArrangeGroupBox.setTitle(_translate("Form", "冷却水管布置方式"))
        self.PipeArrangeYesCheckBox.setText(_translate("Form", "自动布置"))
        self.PipeArrangeNoCheckBox.setText(_translate("Form", "手动输入"))
        self.YesPushButton.setText(_translate("Form", "确定"))
        self.NoPushButton.setText(_translate("Form", "取消"))
        self.titleLabel.setText(_translate("Form", "大体积混凝土基础温度控制"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

